name = "LCTR Creative"
author = "TheAlan404"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14f39db31d709df815386c01c01402ccbd08fe0353e33b9d3ceeab5174c05fc8"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
