name = "LCTR Creative"
author = "TheAlan404"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b345775b2fca0b2d576fe498bbf78d640b7b079521750d5a4c4d04957a17b91e"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
