name = "LCTR Creative"
author = "TheAlan404"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52a72a626877e26c04e6a07c98ebd4af2cc8e712c8b756ff4b81f1b503c8b0d1"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
