name = "LCTR Creative"
author = "TheAlan404"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd25bc34075d50461e1d31c3926fb95d8feb63ff73626809714f46513a72aa95"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
