name = "LCTR Creative"
author = "TheAlan404"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2baee31d550708ae5550b93cb45f08a2218a8c2c3758045a261ec4c187f9ac49"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
